# Aula 02 - Python

## Dados numéricos

In [2]:
# Variável inteira
a = 1 # Cria a variável a com valor 1
print('Valor de a = ' + str(a)) # Imprime um texto "Valor de a = 1", onde a é transformado em string para poder somar com um texto
type(a) # Imprime o tipo de variável que a é

Valor de a = 1


int

In [3]:
# Variável dupla precisão
b = 1.0 # Cria a variável b com valor 1.0
print(b) # Imprime o valor de b
type(b) # Imprime o tipo de variável que b é

1.0


float

In [4]:
# Converter float para int
c = int(b) # Cria a variável c com o valor inteiro da variável b
print(c) # Imprime o valor de c
type(c) # Imprime o tipo de variável que c é

1


int

In [5]:
# Delacrando nan
import numpy as np # Importa a biblioteca numpy e a chama de np
d = np.nan # Cria a variável d com valor NaN (Not a Number)
print(d) # Imprime o valor de d
type(d) # Imprime o tipo de variável que d é

nan


float

In [6]:
# Operação com NaN
e = d*1 # Cria a variável e com o valor de d multiplicado por 1
print(e) # Imprime o valor de e
e = d+1 # Cria a variável e com o valor de d mais 1
print(e) # Imprime o valor de e
e = np.nansum([d,1]) # Cria a variável e utilizando o numpy para fazer a soma de d com 1, de forma que ignore se d for NaN
print(e) # Imprime o valor de e

nan
nan
1.0


## Dados de texto

In [7]:
# Declaração de variável texto
f = 'Fábio' # Cria a variável f com nome Fábio
g = 'Gabriel' # Cria a variável f com nome Gabriel
print(f) # Imprime o nome de f
print(g) # Imprime o nome de g
print(f+g) # Imprime o nome de f junto de g
print(f+' '+g) # Imprime o nome de f junto de g, mas com um espaço entre eles

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica

In [8]:
a == 1 # Imprime se a é igual a 1, se sim, é True, se não, é False

True

In [9]:
h = (a==1) # Cria a variável h com valor de teste de lógica se a é igual a 1, se sim, h é True, se não, h é False
print(h) # Imprime o valor de h
type(h) # Imprime o tipo da variável que h é

True


bool

In [11]:
i = True # Cria a variável i com valor True
type(i) # Imprime o tipo de variável que i é

bool

In [12]:
ii = 'True' # Cria a variável ii com valor de texto True
type(ii) # Imprime o tipo de variável que ii é

str

### Operação de comparação

In [13]:
# Operação ==
a==b # Imprime True se a é igual a b, False se a é diferente de b

True

In [14]:
# Operação ><
a>b # Imprime True se a é maior que b, False se a não é maior que b

False

In [15]:
# Operação !=
a!=b # Imprime True se a é diferente de b, False se a é igual a b

False

In [16]:
# Operação >= ou <=
a>=b # Imprime True se a é maior ou igual a b, False se a não é maior ou igual a b

True

In [17]:
# Soma
a+b # Imprime o valor de a mais b

2.0

In [18]:
# Soma e atribui valor
ab = a+b # Cria a variável ab com valor da variável a mais variável b
print(ab) # Imprime o valor da variável ab

2.0


In [19]:
# Multiplicação 
l = a*b # Não use l como variável, também cria a variável l com a multiplicação de a com b
print("Não use l como nome de variável") # Imprime o texto: Não use l como nome de variável
j = a*b # Cria a variável j com a multiplicação de a com b
print(j) # Imprime o valor da variável j

Não use l como nome de variável
1.0


In [20]:
# Divisão
a/b # Imprime o valor de a dividido por b

1.0

In [21]:
## Potência
5**2 # Imprime o valor de 5 elevado a 2

25

In [23]:
# Operações matemáticas com a biblioteca math
import math # Importa a biblioteca math

math.exp(10) # Com a biblioteca math, imprime o valor do número de Euler elevado a 10

22026.465794806718

In [24]:
math.exp(0) # Com a biblioteca math, imprime o valor do número de Euler elevado a 0

1.0

In [25]:
math.exp(a) # Com a biblioteca math, imprime o valor do número de Euler elevado à variável a

2.718281828459045

In [26]:
math.exp(-10) # Com a biblioteca math, imprime o valor do número de Euler elevado a -10

4.5399929762484854e-05

In [31]:
import math as mt # Importa a biblioteca math e a chama de mt
mt.log(c) # Com a biblioteca math, imprime o valor do logaritmo natural da variável c (1)

0.0

In [32]:
mt.log10(100) # Com a biblioteca math, imprime o valor do logaritmo na base 10 de 100

2.0

## Listas

In [33]:
myFirstList = [1,2,3] # Cria uma lista com os valores 1,2,3
print(myFirstList) # Imprime a lista com seus valores

[1, 2, 3]


In [34]:
# Acessando valores de lista pelo index
print(myFirstList[0]) # Imprime o primeiro valor da lista myFirstList
print(myFirstList[2]) # Imprime o terceiro valor da lista myFirstList

1
3


In [35]:
myFirstList==a # Imprime se a lista myFirstList é igual a a, se sim, imprime True, se não, imprime False

False

In [36]:
myFirstList[0]==a # Imprime se o primeiro valor da lista myFirstList é igual a variável a, se sim, imprime True, se não, imprime False

True

In [37]:
mySecList = [1,a,'c'] # Cria a lista mySecList com valores de 1, variável a, e texto 'c'
print(mySecList) # Imprime a lista com seus valores

[1, 1, 'c']


In [38]:
type(mySecList) # Imprime o tipo de classe que mySecList é

list

In [39]:
type(mySecList[2]) # Imprime o tipo de classe que o terceiro valor da lista mySecList é

str

In [40]:
type(mySecList[1]) # Imprime o tipo de classe que o segundo valor da lista mySecList é

int

## Caminhos = path

In [42]:
path = r"C:\Users\joseh\Documents\GitHub\ENS5173_202401" # Cria path, que apresenta o diretório da pasta ENS5173_202401
print(path) # Imprime path

C:\Users\joseh\Documents\GitHub\ENS5173_202401


In [43]:
path = "C:/Users/joseh/Documents/GitHub/ENS5173_202401" # Cria path, que apresenta o diretório da pasta ENS5173_202401
print(path) # Imprime path

C:/Users/joseh/Documents/GitHub/ENS5173_202401


In [45]:
import os # Importa a biblioteca os que permite mexer no sistema operacional
# Listar arquivos na pasta
os.listdir(path) # Com a biblioteca os, lista os arquivos da última pasta apresentada no path: ENS5173_202401

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Aula01.ipynb',
 'dados',
 'inputs',
 'pyEnv',
 'README.md',
 'scripts',
 'test',
 'test2',
 'Untitled.ipynb']

In [46]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0] # Com a biblioteca os, imprime o primeiro arquivo do diretório de path

'.git'

In [47]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0] # Imprime um caminho do path com o seu primeiro arquivo em seguida

'C:/Users/joseh/Documents/GitHub/ENS5173_202401/.git'

In [48]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0]) # Com a biblioteca os, lista os arquivos do primeiro arquivo da última pasta de path

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [49]:
# Diretório que estou trabalhando
os.getcwd() # Imprime o diretório que está sendo trabalhado

'C:\\Users\\joseh\\Documents\\GitHub\\ENS5173_202401'

In [51]:
# Mudo de diretório para o caminho
os.chdir('C:\\Users\\joseh\\Documents') # Mudar o diretório para Documents
os.getcwd() # Imprime o diretório que está sendo trabalhado

'C:\\Users\\joseh\\Documents'

In [53]:
os.chdir('C:\\Users\\joseh\\Documents\\GitHub\\ENS5173_202401') # Voltar para o diretório de antes
os.getcwd() # Imprime o diretório que está sendo trabalhado

'C:\\Users\\joseh\\Documents\\GitHub\\ENS5173_202401'

In [55]:
# Criando diretório 
new_path = os.getcwd()+'/test' # Cria um caminho new_path de pasta no diretório que está sendo trabalhado com fim /test

if os.path.isdir(new_path): # Teste de lógica, se o caminho new_path já existe como diretório
    print('diretório já existe') # Imprime diretório já existe
else: # Teste de lógica, se o caminho new_path ainda não existe como diretório
    print('Criando diretório '+new_path) # Imprime criando diretório com o nome do diretório em seguida
    os.mkdir(new_path) # Com a biblioteca os, cria o diretório new_path

diretório já existe


In [56]:
# Criando diretório 
new_path = os.getcwd()+'/test2' # Cria um caminho new_path de pasta no diretório que está sendo trabalhado com fim /test2

if os.path.isdir(new_path): # Teste de lógica, se o caminho new_path já existe como diretório
    print('diretório já existe') # Imprime diretório já existe
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file: # Abre o diretório e cria um arquivo copy.txt
        file.write("Your text goes here") # Escreve "Your text goes here" no arquivo copy.txt
else: # Teste de lógica, se o caminho new_path ainda não existe como diretório
    print('Criando diretório '+new_path) # Imprime criando diretório com o nome do diretório em seguida
    os.mkdir(new_path) # Com a biblioteca os, cria o diretório new_path
    with open(new_path+"/copy.txt", "w") as file: # Abre o diretório e cria um arquivo copy.txt
        file.write("Your text goes here") # Escreve "Your text goes here" no arquivo copy.txt

diretório já existe


## Numpy arrays e Pandas DataFrames

In [61]:
import numpy as np # Importa a biblioteca numpy como np
# Criando uma variável numpy
n = np.array(0)  # Cria n como uma variável numpy
type(n) # Imprime o tipo de variável que n é

numpy.ndarray

In [63]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55] # Cria uma lista com nome myThirdList com valores 1, 2, 3, 10, 20, 55
n = np.array(myThirdList) # Cria uma variável n com o numpy a partir de myThirdList
print(n) # Imprime a variável n

[ 1  2  3 10 20 55]


In [64]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10) # Cria uma matriz de 10x10 através da biblioteca numpy com números aleatórios entre 0 e 1
print(n) # Imprime a variável n que é uma matriz
# Dimensões da matrix
print(n.shape) # Imprime as dimensões da variável n

[[1.61073938e-01 3.36358955e-01 4.51688692e-01 9.38731366e-01
  7.01040395e-01 9.75963545e-01 6.63680887e-01 9.46486724e-01
  4.53725588e-01 7.24752363e-01]
 [9.79098664e-01 2.22388733e-01 6.77277550e-01 5.38255454e-01
  2.64375439e-01 1.68606409e-01 5.50497285e-01 8.40491210e-01
  9.95824096e-01 3.21615317e-02]
 [5.58852739e-01 7.46613704e-02 1.86133237e-01 2.46568637e-02
  1.52793064e-01 7.60786875e-01 1.02620049e-01 1.87014400e-01
  3.87908679e-01 3.14897014e-01]
 [5.71039308e-02 9.83580873e-01 7.40250177e-01 8.76593532e-01
  1.36744012e-01 4.95836906e-01 4.80858461e-01 5.38155044e-04
  4.70161151e-01 5.54710469e-01]
 [2.09022060e-01 6.13047395e-02 1.26934173e-01 5.15694877e-01
  7.99322469e-01 9.62624741e-01 8.83376770e-01 1.59340524e-02
  3.81999754e-02 6.02851802e-01]
 [5.19211653e-01 5.84919902e-01 7.99623522e-01 4.49437946e-01
  9.60092279e-01 1.77303462e-01 5.79159833e-01 2.12457816e-01
  3.98353712e-02 7.09627232e-01]
 [3.86299604e-01 2.37050511e-01 9.26204881e-01 8.39598055e

In [65]:
# Acessando valores da matriz
n[0,:] # Imprime a primeira linha da variável n, com o valor de todas as colunas

array([0.16107394, 0.33635895, 0.45168869, 0.93873137, 0.70104039,
       0.97596354, 0.66368089, 0.94648672, 0.45372559, 0.72475236])

In [66]:
n[:,0] # Imprime a primeira coluna da variável n, com o valor de todas as linhas

array([0.16107394, 0.97909866, 0.55885274, 0.05710393, 0.20902206,
       0.51921165, 0.3862996 , 0.15984286, 0.97273718, 0.36442542])

In [70]:
n[:,1:5] # Imprime todas as linhas da variável n, da segundo coluna até a quinta coluna

array([[0.33635895, 0.45168869, 0.93873137, 0.70104039],
       [0.22238873, 0.67727755, 0.53825545, 0.26437544],
       [0.07466137, 0.18613324, 0.02465686, 0.15279306],
       [0.98358087, 0.74025018, 0.87659353, 0.13674401],
       [0.06130474, 0.12693417, 0.51569488, 0.79932247],
       [0.5849199 , 0.79962352, 0.44943795, 0.96009228],
       [0.23705051, 0.92620488, 0.83959806, 0.25638925],
       [0.71086622, 0.3038134 , 0.13940606, 0.53894785],
       [0.03477069, 0.3712976 , 0.69437264, 0.40787949],
       [0.45062754, 0.35479053, 0.34304963, 0.32067033]])

In [71]:
n[0,1:5] # Imprime a primeira linha da variável n, da segundo coluna até a quinta coluna

array([0.33635895, 0.45168869, 0.93873137, 0.70104039])

In [72]:

n[0,-1] # Imprime o valor da célula da primeira linha da variável n, localizado na última coluna

0.724752363457533

In [74]:
n[0,4:-1] # Imprime a primeira linha da variável n, com o valor da quinta coluna até a nona

array([0.70104039, 0.97596354, 0.66368089, 0.94648672, 0.45372559])

In [75]:
n[0,4:] # Imprime a primeira linha da variável n, com o valor da quinta coluna até a última

array([0.70104039, 0.97596354, 0.66368089, 0.94648672, 0.45372559,
       0.72475236])

In [77]:
an = np.log(n*5) # Cria uma matriz com nome an com os valores das células da matriz n como o logaritmo natural do valor de 5 multiplicado por cada célula
print(an) # Imprime a matriz an

[[-0.21645386  0.51986154  0.81467584  1.54621199  1.25424814  1.58510787
   1.19948408  1.55443958  0.81917522  1.28751266]
 [ 1.58831505  0.10610953  1.21976379  0.9900159   0.27905284 -0.17075031
   1.01250466  1.43566913  1.60525327 -1.8275463 ]
 [ 1.02756864 -0.98535454 -0.07185462 -2.09326206 -0.26923288  1.33603589
  -0.66728404 -0.06713175  0.66245258  0.45392828]
 [-1.25344441  1.5928825   1.30867084  1.47772604 -0.38020672  0.90792969
   0.8772556  -5.91792594  0.85475814  1.02012893]
 [ 0.04412243 -1.18246021 -0.45464874  0.9471979   1.38544709  1.57134629
   1.48543444 -2.52985889 -1.65548249  1.10335403]
 [ 0.95399424  1.07315755  1.38582365  0.80968043  1.56871204 -0.12045463
   1.06326112  0.06042609 -1.61356213  1.26642244]
 [ 0.65829588  0.16995588  1.5327781   1.43460591  0.24837942  0.76379918
   1.11707472  0.82617804  1.60305827  1.23753295]
 [-0.22412615  1.26816689  0.41809635 -0.36092641  0.99130146  1.51761429
   0.97670587 -1.84808385  0.00618031  0.33668647]
